"""CLI output-path regression tests — timestamped artifacts.

Model/GPU-free by construction: forward passes and the Benchmark class are
replaced by fakes that write the artifacts the tests then read. Covers:

* the per-run timestamp format generated by ``cli.run_timestamp``;
* the report path derived by ``run()``: ``<TS>`` between stem and suffix
  (no double extension), staying under ``--report-path``'s directory;
* distinct stems producing independent per-run reports (no alias files);
* consistency exit-code propagation;
* a dependency-free compile smoke over the CLI/src entry modules.
"""
import argparse
import re
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# 0. Compile smoke — zero dependencies, always runs.
#    Catches syntax/indentation regressions in modules the pure-NumPy test
#    paths never import (see the docstring above).
# ---------------------------------------------------------------------------
_COMPILE_MODULES = [
    "main.py",
    "cli/benchmark.py",
    "cli/consistency.py",
    "src/benchmark.py",
    "src/consistency.py",
]


@pytest.mark.parametrize("rel_path", _COMPILE_MODULES)
def test_module_compiles(project_root, rel_path):
    source = (project_root / rel_path).read_text(encoding="utf-8")
    compile(source, rel_path, "exec")  # SyntaxError / TabError on regression


# Timestamp format generated once per run at the CLI layer:
#   _YYYYMMDD_HHMMSS_<ms>
_TS = r"\d{8}_\d{6}_\d{3}"


def test_run_timestamp_format():
    """cli.run_timestamp is the single source of the suffix shared by the
    consistency report and the benchmark CSVs — pin its format here."""
    from cli import run_timestamp

    ts = run_timestamp()
    assert re.fullmatch(rf"_{_TS}", ts), ts


def _parse(module, argv):
    parser = argparse.ArgumentParser()
    module.add_parser(parser.add_subparsers(dest="command"))
    return parser.parse_args(argv)


def _touch_model(tmp_path, name):
    p = tmp_path / name
    p.write_bytes(b"")  # existing_validation only checks existence + suffix
    return p


def _heavy_cli(module_name):
    """Import a cli.* module that pulls the ultralytics stack at module level.

    Not a fixture — a plain helper, so tests can pass the module name.
    Opt-in by design: when the heavy runtime is absent the tests skip
    (same pattern as the nncf skip in test_openvino_optional_imports.py).
    """
    pytest.importorskip(
        "ultralytics",
        reason="cli module imports the ultralytics stack at module level",
    )
    return pytest.importorskip(module_name)


# ---------------------------------------------------------------------------
# 1. Benchmark.summary_csv_path — single source of the run filename.
# ---------------------------------------------------------------------------
def test_summary_csv_path_carries_timestamp_suffix():
    from types import SimpleNamespace

    pytest.importorskip("ultralytics")
    from src.benchmark import Benchmark

    # Exercise the property body without __init__ (which needs a real
    # data.yaml): the body only reads self.timestamp_suffix.
    self_ts = SimpleNamespace(timestamp_suffix="_20260928_101530_421")
    assert (
        Benchmark.summary_csv_path.fget(self_ts)
        == "results/benchmark_summary_20260928_101530_421.csv"
    )
    # Library back-compat: empty suffix keeps the unsuffixed fixed path.
    self_empty = SimpleNamespace(timestamp_suffix="")
    assert Benchmark.summary_csv_path.fget(self_empty) == "results/benchmark_summary.csv"


# ---------------------------------------------------------------------------
# 2. consistency run() — --report-path honored, <TS> between stem and suffix,
#    exit-code propagation.
# ---------------------------------------------------------------------------
class _FakeConsistencyRun:
    """Stand-in for validate_consistency: records the requested report_path,
    writes a minimal report, returns it (so run() can propagate the verdict)."""

    def __init__(self):
        self.calls = []

    def __call__(self, **kwargs):
        self.calls.append(kwargs)
        import json

        report_path = Path(kwargs["report_path"])
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(
            json.dumps({"overall_pass": self.overall_pass, "mode": kwargs["mode"]}),
            encoding="utf-8",
        )
        return {"overall_pass": self.overall_pass}

    overall_pass = True


def _consistency_args(tmp_path, cc, extra=()):
    pt = _touch_model(tmp_path, "ref.pt")
    onnx = _touch_model(tmp_path, "cmp.onnx")
    data = tmp_path / "data"
    data.mkdir(exist_ok=True)
    return _parse(cc, [
        "consistency",
        "--model1", str(pt),
        "--model2", str(onnx),
        "--imgs-input", str(data),
        "--report-path", str(tmp_path / "results" / "consistency_report.json"),
        *extra,
    ])


def test_consistency_report_path_is_timestamped_under_given_dir(tmp_path, monkeypatch):
    cc = _heavy_cli("cli.consistency")
    fake = _FakeConsistencyRun()
    monkeypatch.setattr(cc, "validate_consistency", fake)
    monkeypatch.chdir(tmp_path)  # stray cwd writes would land here, not the repo

    rc = cc.run(_consistency_args(tmp_path, cc))
    assert rc == 0

    report_path = Path(fake.calls[0]["report_path"])
    # Must stay under --report-path's parent directory.
    assert report_path.parent == tmp_path / "results"
    # <TS> goes between stem and suffix — no double extension.
    assert re.fullmatch(rf"consistency_report_{_TS}\.json", report_path.name), report_path.name
    assert report_path.exists()


def test_consistency_distinct_stems_keep_independent_reports(tmp_path, monkeypatch):
    """Runs with distinct --report-path stems each leave their own
    timestamped report, and no fixed-name alias file is written."""
    cc = _heavy_cli("cli.consistency")
    fake = _FakeConsistencyRun()
    monkeypatch.setattr(cc, "validate_consistency", fake)
    monkeypatch.chdir(tmp_path)

    pt = _touch_model(tmp_path, "ref.pt")
    onnx = _touch_model(tmp_path, "cmp.onnx")
    data = tmp_path / "data"
    data.mkdir(exist_ok=True)

    for stem, mode in (
        ("consistency_tensor", "tensor"),
        ("consistency_detection", "detection"),
    ):
        args = _parse(cc, [
            "consistency",
            "--model1", str(pt),
            "--model2", str(onnx),
            "--imgs-input", str(data),
            "--mode", mode,
            "--report-path", str(tmp_path / "results" / f"{stem}.json"),
        ])
        assert cc.run(args) == 0

    # Both stems' timestamped reports survive independently, and each fake
    # run wrote its own mode into its own report.
    reports = sorted((tmp_path / "results").glob("consistency_*_2*.json"))
    assert len(reports) == 2
    by_mode = {r.read_text(encoding="utf-8"): r for r in reports}
    assert any('"mode": "tensor"' in t for t in by_mode)
    assert any('"mode": "detection"' in t for t in by_mode)
    # No fixed-name alias of any stem was created.
    assert not list((tmp_path / "results").glob("*_latest*"))


def test_consistency_exit_code_propagation(tmp_path, monkeypatch):
    cc = _heavy_cli("cli.consistency")
    fake = _FakeConsistencyRun()
    monkeypatch.setattr(cc, "validate_consistency", fake)
    monkeypatch.chdir(tmp_path)

    rc = cc.run(_consistency_args(tmp_path, cc))
    assert rc == 0

    # FAIL verdict propagates to exit code 1 through the same path.
    fake.overall_pass = False
    rc = cc.run(_consistency_args(tmp_path, cc))
    assert rc == 1


# ---------------------------------------------------------------------------
# 3. benchmark run() — one timestamp shared by the summary CSV + per-class CSVs.
# ---------------------------------------------------------------------------
class _FakeBenchmark:
    """Stand-in for src.benchmark.Benchmark: records constructor kwargs and
    writes a summary CSV at the suffixed path, mirroring the real contract."""

    calls = []

    def __init__(self, **kwargs):
        _FakeBenchmark.calls.append(kwargs)
        self.timestamp_suffix = kwargs["timestamp_suffix"]

    @property
    def summary_csv_path(self):
        return f"results/benchmark_summary{self.timestamp_suffix}.csv"

    def run_all(self, model_dict):
        Path("results").mkdir(parents=True, exist_ok=True)
        Path(self.summary_csv_path).write_text("Backend\nonnx_fp32\n", encoding="utf-8")
        return {"onnx_fp32": {}}


def test_benchmark_timestamp_flows_to_summary(tmp_path, monkeypatch):
    cb = _heavy_cli("cli.benchmark")
    _FakeBenchmark.calls = []
    monkeypatch.setattr(cb, "Benchmark", _FakeBenchmark)
    monkeypatch.chdir(tmp_path)

    onnx = _touch_model(tmp_path, "m.onnx")
    data = tmp_path / "data"
    data.mkdir(exist_ok=True)
    args = _parse(cb, [
        "benchmark",
        "--model", f"onnx_fp32:{onnx}",
        "--imgs-input", str(data),
    ])
    cb.run(args)

    # One timestamp per run, generated at the CLI layer (exact format,
    # including the leading underscore that the property concatenates).
    ts = _FakeBenchmark.calls[0]["timestamp_suffix"]
    assert re.fullmatch(rf"_{_TS}", ts), ts

    summary = tmp_path / "results" / f"benchmark_summary{ts}.csv"
    assert summary.exists()
    # No fixed-name alias is written alongside the timestamped summary.
    assert not (tmp_path / "results" / "benchmark_summary_latest.csv").exists()
